# Generated by Django 4.2.7 on 2023-11-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_update_at_ticket_updated_at_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tickets.tech'),
        ),
    ]
